name: Check Markdown Links

on:
  push:
    paths:
      - 'book/**'
  pull_request:
    paths:
      - 'book/**'
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run link validator
        run: npm run check:links

      - name: Upload link check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: link-check-results
          path: link-check-results.txt
          retention-days: 7
